### ISSUE TITLE
Monokai? Doesn't work for me

### ISSUE THREAD

**Issue by Wikunia** [getgrav/grav-plugin-highlight#1]
Hey guys,

I wanna start a blog and your lib is one of the things that I need so first of all thanks!
Tried some things yesterday but all I saw was a simple code block, so disabled was like enabled.
Today I simply changed the theme to `github` and everything works fine. Maybe there is an error with your "default" theme `monokai` so you might want to check it out! 

Just an idea: For the user it would be nice to have some screenshots, maybe a gallery of the favorite themes :) 

Have a nice day!

**Comment by Tele-Pet** [comment]
`monokai` is working ok for me.  I created a `highlight.yaml` ( `/user/config/plugins/highlight.yaml`) and have the following:

```
enabled: true
theme: monokai
```

That said, I initially spelled `monokai` like it's spelled in the [Usage Example](https://github.com/getgrav/grav-plugin-highlight#usage): `monakai`:

```
---
title: Sample Code With Custom Theme
highlight:
    theme: monakai
---
```

Once I adjusted the spelling, it seemed to work ok.  I doubt this is the problem @Wikunia is having, but wanted to comment on this just to be sure.

**Comment by flaviocopes** [comment]
Definitely this is the issue, thanks also tricked me!

**Comment by ghost** [comment]
Not that it really matters, but this is actually spelled wrong in the highlight plugin too:
![](https://cloud.githubusercontent.com/assets/5648875/16634367/ebbe491c-4392-11e6-8088-1bb7672ef534.png)

**Comment by flaviocopes** [comment]
@barryanders fixed now, thanks
