### ISSUE TITLE
Get rid of Box around Syntax Highlighting Block

### ISSUE THREAD

**Issue by ghost** [getgrav/grav-plugin-highlight#10]
I searched but not able to find how the box is defined in CSS.
Currently the code is embedded in a box which I'd like to get rid of and have it look like on GRAV blog.

![image](https://cloud.githubusercontent.com/assets/26277943/23706376/381cdf12-040e-11e7-9984-dd206f290641.png)

**Comment by rhukster** [comment]
It's just some styling in Antimatter theme, it has nothing to do with this plugin itself.
