### ISSUE TITLE
Line numbers not working

### ISSUE THREAD

**Issue by boredomwontgetus** [getgrav/grav-plugin-highlight#14]
I use a pretty vanilla version of grav and the plugin works as expected but not for line numbers.

highlight:
  lines: true

Does not change anything. 
Line numbers are just not displayed.

I tested this on multiple themes.

**Comment by rhukster** [comment]
This was a user contributed PR https://github.com/getgrav/grav-plugin-highlight/pull/12

@OleVik can you shed any light?  cheers.

**Comment by OleVik** [comment]
@boredomwontgetus What errors are you getting in the browser's console? The `highlightjs-line-numbers.min.js`-file is a tiny addition known to be compatible with highlight.js, but debugging requires a bit more information: What version of Grav, the Highlight-plugin, and your theme are you currently using?

**Comment by boredomwontgetus** [comment]
@OleVik 
Thats the thing that confuses me a bit...I dont get any errors in the Browsers (chromium) console.

Grav v1.3.7
Highlight Plugin v1.3.1
Theme Bootstrap v1.6.0

Thanks for your quick response

**Comment by boredomwontgetus** [comment]
Ok! Looking at  the PR linked by @rhukster it looks like this was introduced in Highlighter version 1.3.2. So, I guess an update should do. Will try that tomorrow.

**Comment by OleVik** [comment]
Indeed, it was released with 1.3.2, which seems to not be entirely released. @rhukster I bumped the version in the PR, but release has not been made for 1.3.2; wanna add a date to that changelog and release it? Should be May 29th.

**Comment by rhukster** [comment]
I've just release v1.3.2

**Comment by boredomwontgetus** [comment]
Thank you! Works as expected in 1.3.2. Sorry for raising an issue.
I should have gone through the PRs first.

**Comment by rhukster** [comment]
No prob, actually did raise the issue that we had a release pending :)
