### ISSUE TITLE
Background Color doesn't apply in the whole frame

### ISSUE THREAD

**Issue by ghost** [getgrav/grav-plugin-highlight#15]
Hi @rhukster ,

Can you help me, I use the theme learn 2, with the plugin highlight, and as you can see on the screen the color of the theme highlight doesn't apply in the whole frame of the `pre code`, of course I tried all themes, the issue is the same.

![image](https://user-images.githubusercontent.com/26366663/33212559-097823a4-d124-11e7-83ac-bee1a94b82ab.png)

You can view this issue on my website directly : [https://stnetwork.fr/linux/centos/centmin-mod-lemp-web-stack-yum-updates-auto-centos-7#yum-update](https://stnetwork.fr/linux/centos/centmin-mod-lemp-web-stack-yum-updates-auto-centos-7#yum-update)

thanks in advance !

**Comment by softyoda** [comment]
Exactly the same issue, there is a ``<pre>``
Did you found a way to solve this ?
