### ISSUE TITLE
Copy link scroll page to top

### ISSUE THREAD

**Issue by HugoGresse** [getgrav/grav-plugin-highlight#2]
When I click on the copy link of a highlight button, the page scroll to top. There is no console error, the text is correctly copied in my clipboard

Grav RC5, Highlight plugin v1.2.0 with the RTFM theme

**Comment by HugoGresse** [comment]
This happen in Firefox and not in Chrome

**Comment by flaviocopes** [comment]
That's a feature of the Learn2 Theme, not something provided by this plugin. But, on the Learn site it works fine to me on Firefox.
