### ISSUE TITLE
highlight.js outdated

### ISSUE THREAD

**Issue by archfrog** [getgrav/grav-plugin-highlight#22]
Thanks for this plugin, which is crucial for me as I often publish code.

I can see that the [highlight.js demo](https://highlightjs.org/static/demo/) has a style/theme that I'd love to use, but which isn't included in the Grav Highlight plugin.

Any chance that you can update the plugin to use the most recent version of `highlight.js`?

If not, do you accept sensible pull requests?  I already manually added the new styles to my project but only spent energy on adding the `A 11 Y Dark` style/theme to `blueprints.yaml` as that was the one I was looking for.

P.S. I assume I'll have to redo my local patches once you make a new version, but that's life :-)

**Comment by apiontek** [comment]
I second this - I'd prefer to be able to use the "Night Owl" style, unavailable in the current plugin version.

**Comment by rhukster** [comment]
Update it and submit a pull request. I'll merge...

**Comment by dgellow** [comment]
@rhukster I believe this issue can now be closed, following the merge of #24

**Comment by rhukster** [comment]
Yup, new version released
