### ISSUE TITLE
Opt-in - conditionally enable, not disable

### ISSUE THREAD

**Issue by Lamecarlate** [getgrav/grav-plugin-highlight#26]
Is this possible to have this plugin in "opt-in"? I have a blog with some articles with code, and some without. I would like to enable "highlight" only on those with code, rather than disable it on all the others. My main concern is the JS file, loaded everytime, even when there is no code to highlight. I tried `enabled: false` on config/plugins/highlight.yaml then 
``` 
highlight:
  enabled: true
```
in the frontmatter of my article, but no luck (obviously).

If it's not possible, how can I make that? (via another plugin, or inside the theme)

**Comment by rhukster** [comment]
Unfortunately that wont work. If you disable the plugin, no logic is ever run.  Currently there is no way to opt-in.

**Comment by Lamecarlate** [comment]
OK. Well, I can live with that for now :) Thanks!

(sorry for the late answer, I didn't receive an e-mail…)
