### ISSUE TITLE
[IMPROVEMENT] Specify the language in code declaration

### ISSUE THREAD

**Issue by HugoGresse** [getgrav/grav-plugin-highlight#3]
As GitHub wiki allow, it will be great to be able to specify the language we want to highlight as this : 

``````
    ```java
    public abstract void thisIsJava();
    ````
``````

Highlight already allow [language specification](http://highlightjs.readthedocs.org/en/latest/css-classes-reference.html#language-names-and-aliases).  

This will prevent weird colorisation like 
![capture d ecran 2015-12-16 a 10 17 59](https://cloud.githubusercontent.com/assets/662377/11837105/2ee760a6-a3df-11e5-9118-7e99115a57eb.png)

**Comment by flaviocopes** [comment]
This is already provided by the plugin. Code detection works fine, just tested.

**Comment by HugoGresse** [comment]
Thanks for your answer. How do you specify the code language in Markdown so? @flaviocopes

**Comment by flaviocopes** [comment]
In the way you already did. I tried adding php code or javascript code, with the correct language tag it highlights it correctly.
