### ISSUE TITLE
How to add new language?

### ISSUE THREAD

**Issue by s22-tech** [getgrav/grav-plugin-highlight#33]
Is there a way to add a language to this plugin?  I'd like to add AppleScript, which is supported by Prism, but not included here.

Thanks.

**Comment by rhukster** [comment]
Frankly it's a bit of a manual process, as the whole JS package has to be rebuilt to include the language.  Would be amazing if it was modular, but alas, it's not, it's a monolithic package.  

Please create a new issue that specifcally requests AppleScript to be added.
