### ISSUE TITLE
Backend use?

### ISSUE THREAD

**Issue by ghost** [getgrav/grav-plugin-highlight#6]
Why not let this be used on the admin side too? That'd be cool.
![](https://cloud.githubusercontent.com/assets/5648875/16634752/c19ec11e-4394-11e6-9ca3-7bb06301b306.png)

**Comment by w00fz** [comment]
The problem with that is the themes of the code highlight don't necessary match the themes of the editor we use (currently codemirror).

**Comment by flaviocopes** [comment]
Maybe we can provide some choice of built-in color schemes for the admin editor, even simply a dark alternative, as part of the UI customization in Admin

**Comment by w00fz** [comment]
It can be changed already via yaml for any markdown field, by setting the `codemirror.theme` option, and manually via js. As an option in admin config should be totally doable.

**Comment by ghost** [comment]
Just an idea. Although I know Grav is already totally awesome. I could see it being useful if someone was writing code in their pages rather than markdown... of course if they were doing that, then they may as well just not use the Admin plugin, lol.

**Comment by flaviocopes** [comment]
Oh you mean adding code snippets into the page? I thought you were meaning changing the color scheme.

I think it can't be done "live" while editing very easily, and it's quite a specific use case to build it into the editor.

**Comment by ghost** [comment]
No I did mean the color scheme.

**Comment by flaviocopes** [comment]
Ok thanks for clarifying, I understood something else. Yes, color schemes might be nice to have in Admin.

**Comment by ghost** [comment]
Ah, I accidentally closed it earlier on my phone. Anyway, rereading my post where I mentioned having an idea, I see how I could have misled you. I was referring to the idea of having color schemes as mentioned in the first post. In that context I imagine it makes more sense.

**Comment by ghost** [comment]
Err, I was just checking my open issues. This seems kind of pointless to me now, and I hate leaving it open for so long so I'll close it.
