### ISSUE TITLE
Putting JS to the bottom

### ISSUE THREAD

**Issue by hubionmac** [getgrav/grav-plugin-highlight#8]
`$this->grav['assets']->addJs('plugin://highlight/js/highlight.pack.js',array('group' => 'bottom' ));
`

would put the javascript file to the end of the page... that could help tweaking page-speed =)

**Comment by rhukster** [comment]
Unfortunatley this requires the theme to have a 'bottom' group.  Most don't have this.  if it doesn't the CSS/JS won't load.  The benefit is minimal anyway.
